### ISSUE TITLE
Uncaught exception in contact form

### ISSUE THREAD

**Issue by angelosa** [mamedev/www.mamedev.org#22]
https://www.mamedev.org/contact.php

Selecting "I've made some changes to the source code and would like to submit them." will throw uncaught exceptions with stack trace:

```Fatal error: Uncaught TypeError: MWExceptionHandler::rollbackMasterChangesAndLog(): Argument #1 ($e) must be of type Exception, Error given, called in /home/mamedev/wiki.mamedev.org/public_html/includes/exception/MWExceptionHandler.php on line 137 and defined in /home/mamedev/wiki.mamedev.org/public_html/includes/exception/MWExceptionHandler.php on line 111```

```TypeError: MWExceptionHandler::rollbackMasterChangesAndLog(): Argument #1 ($e) must be of type Exception, Error given, called in /home/mamedev/wiki.mamedev.org/public_html/includes/exception/MWExceptionHandler.php on line 137 in /home/mamedev/wiki.mamedev.org/public_html/includes/exception/MWExceptionHandler.php on line 111```

It attempts to redirect to https://wiki.mamedev.org/index.php?title=Submitting_Source_Code which should point to https://wiki.mamedev.org/index.php/Contributing_to_MAME instead?

ETA: "I have a new ROM dump that I would like to submit." goes to a similar behaviour.

**Comment by stilett0** [comment]
No, the Submitting_Source_Code page had different content, although it's possible that the two pages could be unified.
https://web.archive.org/web/20210805132956/https://wiki.mamedev.org/index.php?title=Submitting_Source_Code

The page is still down due to the wiki being down. @galibert is the only one who can fix the wiki, as it is a hosting issue.

We can maybe create a new page for it to redirect to in the interim, if it will be much longer.

**Comment by Robbbert** [comment]
Seems ok now.
